# -*- coding: utf-8 -*-
"""end.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jl9-5qcmXBIMOS7FekFLYvr8aVwP0F8E
"""

# -------------------------------------------
# FINAL APP.PY — With Real Water Droplet + Collapsible Diagnostics + DePriester Comparison
# -------------------------------------------

import streamlit as st
from fpdf import FPDF
import pandas as pd
import numpy as np

# ---------------------------
# Page Style
# ---------------------------
st.set_page_config(layout="wide", page_title="Dew Point - Mission Control")
NAVY = "#001f3f"

st.markdown(
    f"""
    <style>
    .main-title {{
        color: {NAVY};
        text-align: center;
        font-size: 38px;
        font-weight: 900;
        letter-spacing: 1.5px;
        margin-top: 8px;
    }}
    .subtitle {{
        color: {NAVY};
        text-align: center;
        font-size: 14px;
        margin-top: -6px;
        opacity: 0.95;
    }}
    .card {{
        padding: 16px;
        border-radius: 12px;
        background: #f7f9fc;
        border: 1px solid #d8e2ec;
    }}

    /* REAL WATER DROPLET */
    .droplet {{
        width: 160px;
        height: 220px;
        margin: 0 auto;
        background: linear-gradient(180deg, #4fc3f7, #0288d1);
        clip-path: path("M 80 0 C 125 70 160 130 160 170 C 160 215 125 245 80 245 C 35 245 0 215 0 170 C 0 130 35 70 80 0 Z");
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
        font-weight: 900;
        font-size: 24px;
        text-shadow: 0 0 6px rgba(0,0,0,0.5);
    }}

    .muted {{
        color: #6b7b8a;
        font-size: 13px;
    }}
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown("<div class='main-title'>DEW CONTROL PANEL</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Dew Point Simulation Tool — Natural Gas Systems</div>", unsafe_allow_html=True)


# ---------------------------
# Antoine Database
# ---------------------------
ANTOINE_DB = {
    "n-Butane": {"A": 13.6698, "B": 2154.90, "C": 238.789},
    "iso-Butane": {"A": 13.8254, "B": 2241.00, "C": 273.70},
    "n-Pentane": {"A": 13.7667, "B": 2451.88, "C": 230.00},
    "n-Hexane": {"A": 13.8622, "B": 2696.10, "C": 224.37},
    "n-Heptane": {"A": 13.8629, "B": 2916.00, "C": 216.327},
    "n-Octane": {"A": 13.9346, "B": 3133.91, "C": 216.00},
    "n-Nonane": {"A": 13.9703, "B": 3351.61, "C": 216.232},
    "n-Decane": {"A": 13.9748, "B": 3442.73, "C": 215.980},
    "Water": {"A": 16.3872, "B": 3885.70, "C": 230.170},
}


# ---------------------------
# Antoine Equation
# ---------------------------
def antoine_vp_atm(T_c, A, B, C):
    try:
        denom = T_c + C
        if abs(denom) < 1e-9:
            return 0.0
        log10P = A - B / denom
        return (10 ** log10P) / 760.0
    except:
        return 0.0


# ---------------------------
# Sum of partial pressures
# ---------------------------
def Psum(T_c, x_list, antoine_list):
    Psats = [antoine_vp_atm(T_c, A, B, C) for (A, B, C) in antoine_list]
    return sum(x * p for x, p in zip(x_list, Psats)), Psats


# ---------------------------
# Dewpoint Solver (Bisection)
# ---------------------------
def dewpoint_bisection(P_total, x_list, antoine_list, T_low=-120, T_high=200, tol=1e-5, max_iter=250):
    diag = {"mid_points": []}

    P_low, Ps_low = Psum(T_low, x_list, antoine_list)
    P_high, Ps_high = Psum(T_high, x_list, antoine_list)
    diag["P_low"] = P_low
    diag["P_high"] = P_high
    diag["T_low"] = T_low
    diag["T_high"] = T_high

    if P_high < P_total:
        status = "No solution in range: P_sum(T_high) < P_total"
        partials = [x * p for x, p in zip(x_list, Ps_high)]
        y = [p / P_total for p in partials]
        return None, partials, y, 0, status, diag

    if P_low > P_total:
        status = "Dew point below T_low"
        partials = [x * p for x, p in zip(x_list, Ps_low)]
        y = [p / P_total for p in partials]
        return None, partials, y, 0, status, diag

    tL, tH = T_low, T_high
    iters = 0
    while iters < max_iter:
        tM = 0.5 * (tL + tH)
        Pm, Ps_m = Psum(tM, x_list, antoine_list)
        diag["mid_points"].append((tM, Pm))

        if abs(Pm - P_total) <= tol:
            status = "Converged"
            partials = [x * p for x, p in zip(x_list, Ps_m)]
            y = [p / P_total for p in partials]
            diag["P_mid"] = Pm
            return tM, partials, y, iters + 1, status, diag

        if Pm > P_total:
            tH = tM
        else:
            tL = tM

        iters += 1

    status = "Max iterations reached"
    partials = [x * p for x, p in zip(x_list, Ps_m)]
    y = [p / P_total for p in partials]
    diag["P_mid"] = Pm
    return tM, partials, y, iters, status, diag


# ---------------------------
# PDF Report
# ---------------------------
def build_pdf_bytes(results):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=13)
    pdf.cell(0, 10, "Dew Point Simulation Report", ln=True, align="C")
    pdf.ln(5)
    pdf.set_font("Arial", size=11)

    pdf.cell(0, 8, f"Components: {results['components']}", ln=True)
    pdf.cell(0, 8, f"Mole Fractions (x): {results['x_list']}", ln=True)
    pdf.cell(0, 8, f"Pressure: {results['P_input']} {results['P_unit']} ({results['P_atm']:.6f} atm)", ln=True)
    pdf.ln(5)

    if results["T_dp"] is not None:
        pdf.cell(0, 8, f"Dew Point Temp: {results['T_dp']:.4f} °C", ln=True)
    else:
        pdf.cell(0, 8, "Dew Point Temp: NOT FOUND", ln=True)

    pdf.ln(5)
    pdf.cell(0, 8, "Partial Pressures (atm):", ln=True)
    for c, p in zip(results["components"], results["partials"]):
        pdf.cell(0, 7, f"- {c}: {p:.6f}", ln=True)

    pdf.ln(4)
    pdf.cell(0, 8, "Vapor Mole Fractions (y):", ln=True)
    for c, y in zip(results["components"], results["y_list"]):
        pdf.cell(0, 7, f"- {c}: {y:.6f}", ln=True)

    pdf.ln(5)
    pdf.cell(0, 8, f"Status: {results['status']} | Iterations: {results['iters']}", ln=True)

    return pdf.output(dest="S").encode("latin1")


# ---------------------------
# UI — Inputs (Left)
# ---------------------------
left, right = st.columns([2, 1])

with left:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("Input Parameters")

    comp_list = list(ANTOINE_DB.keys())
    c1 = st.selectbox("Component 1", comp_list)
    c2 = st.selectbox("Component 2", comp_list, index=1)

    mode = st.radio("Antoine constants mode:", ("Use Database Constants", "Manual Input (For Perry's Handbook Values)"))

    with st.expander("📘 Antoine Constants Table (Van Ness)"):
        st.table({
            "Component": comp_list,
            "A": [ANTOINE_DB[k]["A"] for k in comp_list],
            "B": [ANTOINE_DB[k]["B"] for k in comp_list],
            "C": [ANTOINE_DB[k]["C"] for k in comp_list],
        })

    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown(f"#### {c1} constants")
        if mode == "Use Database Constants":
            A1 = st.number_input("A", value=float(ANTOINE_DB[c1]["A"]), disabled=True)
            B1 = st.number_input("B", value=float(ANTOINE_DB[c1]["B"]), disabled=True)
            C1 = st.number_input("C", value=float(ANTOINE_DB[c1]["C"]), disabled=True)
        else:
            A1 = st.number_input("A", value=0.0, key="A1_manual")
            B1 = st.number_input("B", value=0.0, key="B1_manual")
            C1 = st.number_input("C", value=0.0, key="C1_manual")

    with col_b:
        st.markdown(f"#### {c2} constants")
        if mode == "Use Database Constants":
            A2 = st.number_input("A ", value=float(ANTOINE_DB[c2]["A"]), disabled=True)
            B2 = st.number_input("B ", value=float(ANTOINE_DB[c2]["B"]), disabled=True)
            C2 = st.number_input("C ", value=float(ANTOINE_DB[c2]["C"]), disabled=True)
        else:
            A2 = st.number_input("A ", value=0.0, key="A2_manual")
            B2 = st.number_input("B ", value=0.0, key="B2_manual")
            C2 = st.number_input("C ", value=0.0, key="C2_manual")

    # Mole Fractions
    x1 = st.slider(f"{c1} mole fraction (x1)", 0.0, 1.0, 0.60)
    x2 = round(1 - x1, 6)
    st.markdown(f"<div class='muted'>{c2} mole fraction (x2) = {x2}</div>", unsafe_allow_html=True)

    # Pressure
    p_val = st.number_input("Pressure value", value=20.0)
    p_unit = st.selectbox("Pressure unit", ["bar", "atm", "kPa", "mmHg"])

    # ---------------------------
    # DePriester options (comparison)
    # ---------------------------
    st.markdown("---")
    st.subheader("DePriester Comparison (optional)")
    st.markdown("Two modes: quick approx (auto), or upload a digitized DePriester K-table CSV for accurate chart lookup.")
    use_depriester = st.checkbox("Enable DePriester comparison", value=False)

    dp_csv = None
    if use_depriester:
        dp_csv = st.file_uploader("Upload DePriester CSV (optional). Format: first column 'T' (°C), then component columns named exactly as in DB.", type=["csv"])
        st.markdown("<div class='muted'>If no CSV is provided, a quick proxy (K ≈ Psat / P) will be used for comparison.</div>", unsafe_allow_html=True)

    # ---------------------------
    # Run button
    # ---------------------------
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("🎮 START SIMULATION"):

        if mode == "Use Database Constants":
            A1v, B1v, C1v = ANTOINE_DB[c1].values()
            A2v, B2v, C2v = ANTOINE_DB[c2].values()
        else:
            A1v = st.session_state.get("A1_manual", 0.0)
            B1v = st.session_state.get("B1_manual", 0.0)
            C1v = st.session_state.get("C1_manual", 0.0)
            A2v = st.session_state.get("A2_manual", 0.0)
            B2v = st.session_state.get("B2_manual", 0.0)
            C2v = st.session_state.get("C2_manual", 0.0)

        unit_map = {"atm": 1, "bar": 0.986923, "kPa": 0.00986923, "mmHg": 1/760}
        P_total = p_val * unit_map[p_unit]

        Tdp, partials, y, iters, status, diag = dewpoint_bisection(
            P_total,
            [x1, x2],
            [(A1v, B1v, C1v), (A2v, B2v, C2v)]
        )

        # Prepare DePriester comparison results
        depriester_result = None
        depriester_table = None

        if use_depriester:
            # Quick approximation: K_approx = Psat(Tdp) / P_total  (proxy)
            if Tdp is not None:
                # compute Psat at Tdp for each component
                Psats_at_Tdp = [antoine_vp_atm(Tdp, A1v, B1v, C1v), antoine_vp_atm(Tdp, A2v, B2v, C2v)]
                K_approx = [Psat / P_total if P_total > 0 else None for Psat in Psats_at_Tdp]

                depriester_result = {
                    "T_dp": Tdp,
                    "K_approx": K_approx,
                    "Psats_at_Tdp": Psats_at_Tdp
                }
            else:
                depriester_result = {
                    "T_dp": None,
                    "note": "Antoine dew point not found — cannot compute DePriester proxy."
                }

            # If CSV uploaded, parse it and interpolate K-values at Tdp
            if dp_csv is not None:
                try:
                    df_dp = pd.read_csv(dp_csv)
                    if "T" not in df_dp.columns:
                        st.error("CSV must include 'T' column (°C). Please upload correct DePriester CSV.")
                        dp_csv = None
                    else:
                        # Ensure columns for selected components exist
                        # Use exact keys from ANTOINE_DB (component names)
                        required_cols = [c1, c2]
                        missing_cols = [c for c in required_cols if c not in df_dp.columns]
                        if missing_cols:
                            st.error(f"CSV is missing DePriester column(s) for: {', '.join(missing_cols)}. Column names must match component names.")
                            dp_csv = None
                        else:
                            # Interpolate K-values at Tdp
                            T_vals = df_dp["T"].values.astype(float)
                            depriester_interp = {}
                            if Tdp is not None:
                                for comp in required_cols:
                                    K_col = df_dp[comp].values.astype(float)
                                    K_at_T = float(np.interp(Tdp, T_vals, K_col))
                                    depriester_interp[comp] = K_at_T
                                depriester_table = {
                                    "T_vals": T_vals,
                                    "raw_df": df_dp,
                                    "interp_K": depriester_interp
                                }
                            else:
                                depriester_table = {"interp_K": None, "note": "Tdp not found"}
                except Exception as e:
                    st.error(f"Failed to read CSV: {e}")
                    dp_csv = None

        # save results in session
        st.session_state["results"] = {
            "components": [c1, c2],
            "x_list": [x1, x2],
            "P_input": p_val,
            "P_unit": p_unit,
            "P_atm": P_total,
            "T_dp": Tdp,
            "partials": partials,
            "y_list": y,
            "iters": iters,
            "status": status,
            "diagnostics": diag,
            "depriester_enabled": use_depriester,
            "depriester_result": depriester_result,
            "depriester_table": depriester_table
        }

    st.markdown("</div>", unsafe_allow_html=True)


# ---------------------------
# UI — Output (Right)
# ---------------------------
with right:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("Simulation Output")

    res = st.session_state.get("results", None)

    if not res:
        st.info("Run a simulation to view results.")
    else:

        # ---------------------------
        # REAL WATER DROPLET DISPLAY
        # ---------------------------
        temp_display = "N/A" if res["T_dp"] is None else f"{res['T_dp']:.2f}°C"
        st.markdown(f"<div class='droplet'>{temp_display}</div>", unsafe_allow_html=True)

        st.write("### Partial Pressures (atm)")
        st.table({
            "Component": res["components"],
            "Partial Pressure": [f"{p:.6f}" for p in res["partials"]]
        })

        st.write("### Vapor Mole Fractions (y)")
        st.table({
            "Component": res["components"],
            "y": [f"{y:.6f}" for y in res["y_list"]]
        })

        # ---------------------------
        # COLLAPSIBLE DIAGNOSTICS
        # ---------------------------
        with st.expander("Show Convergence Diagnostics"):
            st.write(f"**Status:** {res['status']}")
            st.write(f"**Iterations:** {res['iters']}")
            diag = res["diagnostics"]

            st.write(f"- P_sum(@T_low={diag['T_low']} °C) = {diag['P_low']:.6g} atm")
            st.write(f"- P_sum(@T_high={diag['T_high']} °C) = {diag['P_high']:.6g} atm")

            if "P_mid" in diag:
                st.write(f"- P_sum(@T_mid) = {diag['P_mid']:.6g} atm")

            st.write("#### Iteration Trace")
            st.table({
                "T_mid (°C)": [round(t, 5) for (t, _) in diag["mid_points"]],
                "P_sum (atm)": [round(p, 6) for (_, p) in diag["mid_points"]]
            })

        # ---------------------------
        # DePriester Comparison (collapsible)
        # ---------------------------
        if res.get("depriester_enabled", False):
            with st.expander("DePriester Comparison (click to expand)"):
                st.write("**Method note:**\n- Quick proxy uses K ≈ Psat(T_dp) / P_total (a simple comparison proxy).")
                st.write("- For true DePriester chart values, upload a digitized CSV with `T` (°C) as first column and one column per component (column names must match components).")
                depriester_result = res.get("depriester_result", None)
                depriester_table = res.get("depriester_table", None)

                if depriester_result is None:
                    st.write("No DePriester data available.")
                else:
                    if depriester_result.get("T_dp") is None:
                        st.write("Antoine dew point not found — DePriester comparison unavailable.")
                    else:
                        st.write(f"Antoine Dew Point used for comparison: **{depriester_result['T_dp']:.4f} °C**")
                        # show proxy Ks
                        K_approx = depriester_result.get("K_approx", None)
                        Psats_at_Tdp = depriester_result.get("Psats_at_Tdp", None)
                        if K_approx is not None:
                            st.write("### Quick DePriester proxy (K ≈ Psat/P_total) at T_dp")
                            table = {
                                "Component": res["components"],
                                "Psat_at_Tdp (atm)": [f"{p:.6e}" for p in Psats_at_Tdp],
                                "K_proxy": [f"{k:.6e}" if k is not None else "N/A" for k in K_approx]
                            }
                            st.table(table)

                        # if uploaded table exists, show interpolated K
                        if depriester_table is not None and "interp_K" in depriester_table and depriester_table["interp_K"] is not None:
                            st.write("### DePriester CSV interpolation (chart-accurate K-values)")
                            interp = depriester_table["interp_K"]
                            interp_rows = []
                            for comp in res["components"]:
                                K_chart = interp.get(comp, None)
                                # compute percent diff vs K_proxy if available
                                K_proxy_val = None
                                if K_approx is not None:
                                    # find index of component
                                    idx = res["components"].index(comp)
                                    K_proxy_val = K_approx[idx]
                                pct_diff = None
                                if K_chart is not None and K_proxy_val is not None and K_proxy_val != 0:
                                    pct_diff = 100.0 * (K_chart - K_proxy_val) / K_proxy_val
                                interp_rows.append({
                                    "Component": comp,
                                    "K_chart": f"{K_chart:.6e}",
                                    "K_proxy": f"{K_proxy_val:.6e}" if K_proxy_val is not None else "N/A",
                                    "pct_diff (%)": f"{pct_diff:.3f}" if pct_diff is not None else "N/A"
                                })
                            st.table(interp_rows)
                        else:
                            st.markdown("<div class='muted'>No DePriester CSV provided — only quick proxy shown. Upload CSV for chart-accurate K-values.</div>", unsafe_allow_html=True)

        # PDF DOWNLOAD
        pdf_bytes = build_pdf_bytes(res)
        st.download_button(
            "📄 Download PDF Report",
            data=pdf_bytes,
            file_name="dewpoint_report.pdf",
            mime="application/pdf"
        )

    st.markdown("</div>", unsafe_allow_html=True)